package main

import (
	"bytes"
	"fmt"
	"go/format"
)

const doNotEdit = "// Code generated by gostructor-gen. DO NOT EDIT."

// renderFill emits the file holding a type's generated Fill method plus one
// small per-field helper method, so parsing is split across readable methods
// rather than living in one monolithic Fill body.
func renderFill(pkgName string, spec *structSpec) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, doNotEdit)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"reflect\"")
	if spec.needTime {
		fmt.Fprintln(&b, "\t\"time\"")
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "\t\"github.com/goreflect/gostructor\"")
	fmt.Fprintln(&b, "\t\"github.com/goreflect/gostructor/gen\"")
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)

	renderFillType(&b, spec)

	return format.Source(b.Bytes())
}

func renderFillType(b *bytes.Buffer, spec *structSpec) {
	fieldsVar := "_gostructorFields_" + spec.Type
	fmt.Fprintf(b, "// %s is the flattened, resolvable fields of %s, built once so\n", fieldsVar, spec.Type)
	fmt.Fprintln(b, "// each helper pays only a slice index, not a per-call reflect walk. The order")
	fmt.Fprintln(b, "// matches the reflective engine's, which the helpers index into by position.")
	fmt.Fprintf(b, "var %s = gostructor.Fields(reflect.TypeOf(%s{}))\n\n", fieldsVar, spec.Type)

	fmt.Fprintf(b, "// Fill resolves every field of %s from the given sources, in source slice\n", spec.Type)
	fmt.Fprintln(b, "// order, without per-fill reflection. Semantics match")
	fmt.Fprintf(b, "// gostructor.Configure(&c, opts...) exactly. Generated by gostructor-gen.\n")
	fmt.Fprintf(b, "func (c *%s) Fill(opts ...gostructor.Option) error {\n", spec.Type)
	fmt.Fprintln(b, "\trt := gostructor.NewGenRuntime(opts...)")
	for _, f := range spec.Fields {
		fmt.Fprintf(b, "\tif err := c.%s(rt); err != nil {\n", f.method())
		fmt.Fprintln(b, "\t\treturn err")
		fmt.Fprintln(b, "\t}")
	}
	fmt.Fprintln(b, "\treturn nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)

	for _, f := range spec.Fields {
		renderFieldMethod(b, spec.Type, fieldsVar, f)
	}
}

func renderFieldMethod(b *bytes.Buffer, typeName, fieldsVar string, f fieldSpec) {
	fmt.Fprintf(b, "// %s resolves %s.%s.\n", f.method(), typeName, f.Path)
	fmt.Fprintf(b, "func (c *%s) %s(rt *gostructor.GenRuntime) error {\n", typeName, f.method())
	fmt.Fprintf(b, "\tfc := %s[%d]\n", fieldsVar, f.Index)
	fmt.Fprintln(b, "\traw, found, err := rt.ResolveField(fc)")
	fmt.Fprintln(b, "\tif err != nil {")
	fmt.Fprintln(b, "\t\treturn err")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\tif found {")
	fmt.Fprintf(b, "\t\tv, cerr := %s(raw)\n", convCall(f))
	fmt.Fprintln(b, "\t\tif cerr != nil {")
	fmt.Fprintf(b, "\t\t\treturn rt.ConvertError(fc, raw, reflect.TypeOf(c.%s), cerr)\n", f.Path)
	fmt.Fprintln(b, "\t\t}")
	fmt.Fprintln(b, "\t\thv, herr := rt.ApplyHooks(fc, v)")
	fmt.Fprintln(b, "\t\tif herr != nil {")
	fmt.Fprintln(b, "\t\t\treturn herr")
	fmt.Fprintln(b, "\t\t}")
	fmt.Fprintf(b, "\t\ttv, ok := hv.(%s)\n", f.GoType)
	fmt.Fprintln(b, "\t\tif !ok {")
	fmt.Fprintf(b, "\t\t\treturn rt.HookTypeError(fc, hv, reflect.TypeOf(c.%s))\n", f.Path)
	fmt.Fprintln(b, "\t\t}")
	fmt.Fprintf(b, "\t\tc.%s = tv\n", f.Path)
	fmt.Fprintln(b, "\t} else if nerr := rt.NotResolved(fc); nerr != nil {")
	fmt.Fprintln(b, "\t\treturn nerr")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\treturn nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

// convCall is the conversion expression for a field: a dedicated reflection-free
// helper (gen.Int, gen.Duration, …) for the common types, or the generic
// gen.Reflective[T] for the compound and named ones.
func convCall(f fieldSpec) string {
	if f.Reflective {
		return fmt.Sprintf("gen.Reflective[%s]", f.GoType)
	}
	return f.Conv
}

// renderGoldenTest emits TestFillMatchesReflection_<Type>: it fills the same
// struct through the reflective engine and the generated Fill across an env
// fixture and asserts identical values and identical error classification, so a
// divergence fails CI.
func renderGoldenTest(pkgName string, spec *structSpec) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, doNotEdit)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"reflect\"")
	fmt.Fprintln(&b, "\t\"testing\"")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "\t\"github.com/goreflect/gostructor\"")
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)

	renderGoldenTestType(&b, spec)
	return format.Source(b.Bytes())
}

func renderGoldenTestType(b *bytes.Buffer, spec *structSpec) {
	fmt.Fprintf(b, "// TestFillMatchesReflection_%s asserts the generated Fill produces the same\n", spec.Type)
	fmt.Fprintln(b, "// result as the reflective engine for an env-sourced fixture, so the two")
	fmt.Fprintln(b, "// paths cannot drift.")
	fmt.Fprintf(b, "func TestFillMatchesReflection_%s(t *testing.T) {\n", spec.Type)
	for _, f := range spec.Fields {
		// Env is a flat string source, so only the scalar leaves get a fixture;
		// a map/slice/named field is left to its default (or unresolved), which
		// both paths handle identically.
		if !f.Reflective && f.EnvKey != "" {
			fmt.Fprintf(b, "\tt.Setenv(%q, %q)\n", f.EnvKey, f.EnvValue)
		}
	}
	fmt.Fprintln(b)
	fmt.Fprintf(b, "\tvar reflective, generated %s\n", spec.Type)
	fmt.Fprintln(b, "\tsources := func() gostructor.Option {")
	fmt.Fprintln(b, "\t\treturn gostructor.WithSources(gostructor.Env(), gostructor.Default())")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "\t_, errReflect := gostructor.Configure(&reflective, gostructor.WithEngine(gostructor.EngineReflection), sources())")
	fmt.Fprintln(b, "\terrGen := generated.Fill(sources())")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "\tif (errReflect == nil) != (errGen == nil) {")
	// b.WriteString for lines whose emitted content holds %-directives, so
	// go vet does not mistake them for this generator's own format calls.
	b.WriteString("\t\tt.Fatalf(\"error mismatch: reflection=%v generated=%v\", errReflect, errGen)\n")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\tif errReflect != nil {")
	fmt.Fprintln(b, "\t\tif errReflect.Error() != errGen.Error() {")
	b.WriteString("\t\t\tt.Fatalf(\"error text mismatch:\\n reflection=%q\\n generated=%q\", errReflect, errGen)\n")
	fmt.Fprintln(b, "\t\t}")
	fmt.Fprintln(b, "\t\treturn")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\tif !reflect.DeepEqual(reflective, generated) {")
	b.WriteString("\t\tt.Errorf(\"generated Fill diverged:\\n reflection=%+v\\n generated=%+v\", reflective, generated)\n")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}
