// Code generated by gostructor-gen. DO NOT EDIT.

package main

import (
	"reflect"
	"testing"

	"github.com/goreflect/gostructor"
)

// TestFillMatchesReflection_AppConfig asserts the generated Fill produces the same
// result as the reflective engine for an env-sourced fixture, so the two
// paths cannot drift.
func TestFillMatchesReflection_AppConfig(t *testing.T) {
	t.Setenv("SVC_NAME", "example")
	t.Setenv("SVC_PORT", "42")
	t.Setenv("SVC_TIMEOUT", "1s")
	t.Setenv("DB_HOST", "example")
	t.Setenv("DB_REPLICAS", "42")
	t.Setenv("TAGS", "a,b,c")

	var reflective, generated AppConfig
	sources := func() gostructor.Option {
		return gostructor.WithSources(gostructor.Env(), gostructor.Default())
	}

	_, errReflect := gostructor.Configure(&reflective, gostructor.WithEngine(gostructor.EngineReflection), sources())
	errGen := generated.Fill(sources())

	if (errReflect == nil) != (errGen == nil) {
		t.Fatalf("error mismatch: reflection=%v generated=%v", errReflect, errGen)
	}
	if errReflect != nil {
		if errReflect.Error() != errGen.Error() {
			t.Fatalf("error text mismatch:\n reflection=%q\n generated=%q", errReflect, errGen)
		}
		return
	}
	if !reflect.DeepEqual(reflective, generated) {
		t.Errorf("generated Fill diverged:\n reflection=%+v\n generated=%+v", reflective, generated)
	}
}
