// Code generated by gostructor-gen. DO NOT EDIT.

package main

import (
	"reflect"
	"time"

	"github.com/goreflect/gostructor"
	"github.com/goreflect/gostructor/gen"
)

// _gostructorFields_AppConfig is the flattened, resolvable fields of AppConfig, built once so
// each helper pays only a slice index, not a per-call reflect walk. The order
// matches the reflective engine's, which the helpers index into by position.
var _gostructorFields_AppConfig = gostructor.Fields(reflect.TypeOf(AppConfig{}))

// Fill resolves every field of AppConfig from the given sources, in source slice
// order, without per-fill reflection. Semantics match
// gostructor.Configure(&c, opts...) exactly. Generated by gostructor-gen.
func (c *AppConfig) Fill(opts ...gostructor.Option) error {
	rt := gostructor.NewGenRuntime(opts...)
	if err := c.gostructorFillServiceName(rt); err != nil {
		return err
	}
	if err := c.gostructorFillServicePort(rt); err != nil {
		return err
	}
	if err := c.gostructorFillServiceTimeout(rt); err != nil {
		return err
	}
	if err := c.gostructorFillDBHost(rt); err != nil {
		return err
	}
	if err := c.gostructorFillDBReplicas(rt); err != nil {
		return err
	}
	if err := c.gostructorFillLabels(rt); err != nil {
		return err
	}
	if err := c.gostructorFillPorts(rt); err != nil {
		return err
	}
	if err := c.gostructorFillTags(rt); err != nil {
		return err
	}
	return nil
}

// gostructorFillServiceName resolves AppConfig.Service.Name.
func (c *AppConfig) gostructorFillServiceName(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[0]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.String(raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.Service.Name), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.(string)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.Service.Name))
		}
		c.Service.Name = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillServicePort resolves AppConfig.Service.Port.
func (c *AppConfig) gostructorFillServicePort(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[1]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.Int(raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.Service.Port), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.(int)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.Service.Port))
		}
		c.Service.Port = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillServiceTimeout resolves AppConfig.Service.Timeout.
func (c *AppConfig) gostructorFillServiceTimeout(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[2]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.Duration(raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.Service.Timeout), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.(time.Duration)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.Service.Timeout))
		}
		c.Service.Timeout = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillDBHost resolves AppConfig.DB.Host.
func (c *AppConfig) gostructorFillDBHost(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[3]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.String(raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.DB.Host), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.(string)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.DB.Host))
		}
		c.DB.Host = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillDBReplicas resolves AppConfig.DB.Replicas.
func (c *AppConfig) gostructorFillDBReplicas(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[4]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.Uint(raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.DB.Replicas), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.(uint)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.DB.Replicas))
		}
		c.DB.Replicas = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillLabels resolves AppConfig.Labels.
func (c *AppConfig) gostructorFillLabels(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[5]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.Reflective[map[string]string](raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.Labels), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.(map[string]string)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.Labels))
		}
		c.Labels = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillPorts resolves AppConfig.Ports.
func (c *AppConfig) gostructorFillPorts(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[6]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.Reflective[[]int](raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.Ports), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.([]int)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.Ports))
		}
		c.Ports = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}

// gostructorFillTags resolves AppConfig.Tags.
func (c *AppConfig) gostructorFillTags(rt *gostructor.GenRuntime) error {
	fc := _gostructorFields_AppConfig[7]
	raw, found, err := rt.ResolveField(fc)
	if err != nil {
		return err
	}
	if found {
		v, cerr := gen.StringSlice(raw)
		if cerr != nil {
			return rt.ConvertError(fc, raw, reflect.TypeOf(c.Tags), cerr)
		}
		hv, herr := rt.ApplyHooks(fc, v)
		if herr != nil {
			return herr
		}
		tv, ok := hv.([]string)
		if !ok {
			return rt.HookTypeError(fc, hv, reflect.TypeOf(c.Tags))
		}
		c.Tags = tv
	} else if nerr := rt.NotResolved(fc); nerr != nil {
		return nerr
	}
	return nil
}
