on: pull_request
name: CI_dev
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
     - name: Install Go
       if: success()
       uses: actions/setup-go@v2
       with:
        go-version: 1.16.x
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Calc coverage 
       run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        go test ./... -race -coverprofile=coverage.out -covermode=atomic
        cat coverage.out
     - name: Convert coverage to lcov
       uses: jandelgado/gcov2lcov-action@v1.0.0
       with:
            infile: coverage.out
            outfile: coverage.lcov
     - name: Coveralls
       uses: codecov/codecov-action@v1
       with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.lcov #optional
        fail_ci_if_error: true #optional (default = false)
     - name: Go Report Card
       uses: creekorful/goreportcard-action@v0.4
